[package]
name = "gtk-ui"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0"
description = "The transpiler for GtkUI."
homepage = "https://github.com/GtkUI/gtk-ui"

[dependencies]
unescape = "0.1.0"
